# -*- coding: utf-8 -*-
"""Untitled48.hypothesis_testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbvO79bgJdFgLr0_HXZutSZFlgmKv99-
"""

'''
A comapny claims the avergae packet weight is 100 g
we collect a sample of 30 packets and get
sample mean=97.5
sample std=6
sample size=30
we want to test wheather the true mean is different from 100g
'''

#import libraries
import numpy as np
from scipy import stats

#store the values
sample_mean=97.5
population_mean=100
sample_std=6
n=30

standard_error = sample_std / np.sqrt(n)

print("Standard Error =", standard_error)

#calculate the t-statistic
t_stat=(sample_mean-population_mean)/standard_error
print("T statistic=",t_stat)

#calculate p_value
p_value = 2 * (1 - stats.t.cdf(abs(t_stat), df=n-1))

print("P Value =", p_value)

#choose significance level
alpha=0.05

#make a decision
if p_value< alpha:
  print("reject HO")
else:
  print("Fail to reject HO")